"""Generate docs/rules.md from the registry.

The rule reference is the one document guaranteed to rot, because it repeats
information that already exists in code. So it is generated, and CI checks
that the committed copy matches what the registry currently says. A rule whose
``cannot_detect`` changes without the docs changing fails the build.

    python tools/gen_rule_docs.py           # write docs/rules.md
    python tools/gen_rule_docs.py --check   # fail if it is out of date
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from resint.ir.finding import Tier  # noqa: E402
from resint.rules import load_all  # noqa: E402

TARGET = Path(__file__).resolve().parents[1] / "docs" / "rules.md"

FAMILIES = {
    "numbers": (
        "Internal consistency",
        "Pure arithmetic over values the paper reports about itself. No "
        "network, no model, no assumptions about the field.",
    ),
    "stats": (
        "Statistical forensics",
        "Recomputation rather than interpretation. Each of these asks whether "
        "the reported numbers can be true together, not whether the analysis "
        "was the right one.",
    ),
    "bib": (
        "Citation integrity",
        "Resolution against Crossref, OpenAlex, arXiv and Semantic Scholar. "
        "A lookup that fails is reported as unchecked, never as a missing "
        "reference.",
    ),
    "repro": (
        "Paper against code",
        "Requires `--repo`. These compare what the paper says was done "
        "against what the repository would actually do.",
    ),
    "claim": ("Semantic checks", "Model-assisted. Optional; skipped without a provider."),
    "eval": ("Evaluation integrity", "Model-assisted. Optional; skipped without a provider."),
}

HEADER = """<!-- Generated by tools/gen_rule_docs.py. Do not edit by hand. -->

# Rules

Every rule declares what it **cannot** detect. That declaration is mandatory —
the engine refuses to register a rule without one — and it travels with each
finding into `--format json` and `--format sarif`, so the limitation reaches
whatever reads the output.

A rule that knows its own limits is trustworthy. One that implies completeness
is not.

| Tier | Meaning |
|---|---|
| **deterministic** | Computed. No model in the loop, no API key, marked `✓` in output. |
| **model-assisted** | Involves judgement. Optional, skipped silently without a provider, marked `~`. |

Severity shown is the **default**. Rules may escalate or reduce per finding —
a *p*-value off in the fourth decimal is a typo, while one that flips a
significance decision changes what the paper claims.

"""


def _prose(rule) -> tuple[str, str]:
    """Headline and body from the rule module's docstring.

    Rule functions are all named ``check``; the prose that explains a rule
    lives in its module docstring, written as "family/name -- what it
    catches". The id prefix is stripped here since the heading already
    carries it.
    """
    module = sys.modules.get(rule.fn.__module__)
    doc = textwrap.dedent((getattr(module, "__doc__", "") or "")).strip()
    if not doc:
        return "", ""

    paragraphs = [p.strip() for p in doc.split("\n\n") if p.strip()]
    headline = paragraphs[0].replace("\n", " ")
    prefix = f"{rule.id} -- "
    if headline.startswith(prefix):
        headline = headline[len(prefix) :]
    headline = headline[:1].upper() + headline[1:]

    body = "\n\n".join(p.replace("\n", " ") for p in paragraphs[1:])
    return headline, body


def render() -> str:
    registry = load_all()
    out = [HEADER]

    by_family: dict[str, list] = {}
    for rule in registry.all():
        by_family.setdefault(rule.family, []).append(rule)

    counts = {
        "total": len(registry),
        "deterministic": len(registry.by_tier(Tier.DETERMINISTIC)),
        "repo": sum(1 for r in registry.all() if r.needs_repo),
    }
    out.append(
        f"**{counts['total']} rules** — {counts['deterministic']} run with no "
        f"API key, {counts['repo']} need `--repo`.\n\n"
    )

    for family in FAMILIES:
        rules = by_family.get(family)
        if not rules:
            continue
        title, blurb = FAMILIES[family]
        out.append(f"## `{family}/` — {title}\n\n{blurb}\n\n")

        for rule in rules:
            out.append(f"### `{rule.id}`\n\n")
            badges = [f"**{rule.severity.value}**", rule.tier.value]
            if rule.needs_repo:
                badges.append("`--repo`")
            out.append(" · ".join(badges) + "\n\n")

            headline, body = _prose(rule)
            if headline:
                out.append(f"{headline}\n\n")
            if body:
                out.append(f"{body}\n\n")

            out.append(f"**Cannot detect.** {rule.cannot_detect}\n\n")
            out.append(
                "<sub>Requires: "
                + ", ".join(f"`{r}`" for r in rule.requires)
                + "</sub>\n\n"
            )

    return "".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = render()

    if args.check:
        if not TARGET.exists():
            print("docs/rules.md is missing. Run: python tools/gen_rule_docs.py")
            return 1
        if TARGET.read_text(encoding="utf-8") != generated:
            print(
                "docs/rules.md is out of date with the registry.\n"
                "Run: python tools/gen_rule_docs.py"
            )
            return 1
        print("docs/rules.md is up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(Path.cwd())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
